apiVersion: v1
kind: Service
metadata:
  name: minikv-0-client
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: minikv-0
  ports:
    - name: client
      port: 9400
      targetPort: 9400
      nodePort: 30400
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: minikv-1-client
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: minikv-1
  ports:
    - name: client
      port: 9401
      targetPort: 9401
      nodePort: 30401
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: minikv-2-client
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: minikv-2
  ports:
    - name: client
      port: 9402
      targetPort: 9402
      nodePort: 30402
      protocol: TCP
